from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent

VENV_PYTHON = BASE_DIR / ".venv" / "Scripts" / "python.exe"

HOST = "127.0.0.1"
PORT = 8000
SERVER_URL = f"http://{HOST}:{PORT}"
HEALTH_CHECK_URL = SERVER_URL

CONTROL_HOST = "127.0.0.1"
CONTROL_PORT = 8766
CONTROL_URL = f"http://{CONTROL_HOST}:{CONTROL_PORT}"

WINDOW_CONTROL_HOST = CONTROL_HOST
WINDOW_CONTROL_PORT = CONTROL_PORT
WINDOW_CONTROL_URL = CONTROL_URL

JARVIS_WINDOW_SCRIPT = BASE_DIR / "jarvis_window.py"

LOG_DIR = BASE_DIR / "logs"
DATA_DIR = BASE_DIR / "data"

DAEMON_LOG_FILE = LOG_DIR / "jarvis_daemon.log"
TRAY_LOG_FILE = LOG_DIR / "jarvis_tray.log"
WINDOW_LOG_FILE = LOG_DIR / "jarvis_window.log"
UVICORN_LOG_FILE = LOG_DIR / "uvicorn.log"
LOCK_FILE = BASE_DIR / "jarvis_daemon.lock"
WINDOW_STATE_FILE = DATA_DIR / "window_state.json"
WEBVIEW_DATA_DIR = DATA_DIR / "webview"
APP_WINDOW_TITLE = "J.A.R.V.I.S"

DEFAULT_WINDOW_STATE = {
    "x": 0,
    "y": 0,
    "width": 974,
    "height": 1039,
}

CHECK_INTERVAL_SECONDS = 5
STARTUP_TIMEOUT_SECONDS = 30
MAX_RESTART_ATTEMPTS = 3
RESTART_WINDOW_SECONDS = 60
RESTART_DELAY_SECONDS = 3
STABLE_RUNNING_SECONDS = 30

WAKEWORD_DEVICE_NAME = "ReSpeaker 4 Mic Array"
WAKEWORD_HOST_API_NAME = "MME"

WAKEWORD_TARGET_SAMPLE_RATE = 16000
WAKEWORD_TARGET_FRAME_SAMPLES = 1280

WAKEWORD_CAPTURE_SAMPLE_RATE = None

WAKEWORD_CAPTURE_CHANNELS = 6
WAKEWORD_MIC_CHANNEL_INDEX = 0
WAKEWORD_DTYPE = "int16"


WAKEWORD_THRESHOLD = 0.5
WAKEWORD_COOLDOWN_SECONDS = 2.0
WAKEWORD_MODEL_NAME = "hey jarvis"
WAKEWORD_AUDIO_QUEUE_SIZE = 30